name: Disker
version: 1.0
main: me.tyrn11.disker.DiskerPlugin
description: Create custom music discs from YouTube and Spotify links
commands:
  musicdisc:
    description: Create a music disc from a YouTube or Spotify link
    usage: /musicdisc <URL>